package daggerok;

import daggerok.extensions.Args;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        System.out.println(Args.kotlinResult(args));
    }
}
