/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import daggerok.extensions.DOM;
import daggerok.extensions.HtmlBuilder;
import kotlin.Pair;
import kotlin.Unit;
import kotlin.jvm.functions.Function2;
import org.junit.Test;

import java.util.stream.Stream;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AppTest {

  @Test
  public void testAppHasAGreeting() {

    final Function2<? super HtmlBuilder, ? super String, Unit> func = (HtmlBuilder b, String s) -> Unit.INSTANCE;
    final String html = DOM.html(Stream.empty().<Pair<String, String>>toArray(Pair[]::new), new String[0], func);

    assertThat(html, is("<!DOCTYPE html><html></html>"));
  }
}
