/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import daggerok.extensions.Args;
import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testAppHasAGreeting() {
    assertNotNull("app should have a greeting", Args.kotlinResult(new String[0]));
  }
}
