/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import daggerok.extensions.DOM;
import kotlin.Pair;
import kotlin.jvm.functions.Function1;
import org.junit.Test;

import java.util.stream.Stream;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AppTest {

  @Test
  public void testAppHasAGreeting() {

    final Function1<? super String, String> func = string -> string;
    final String html = DOM.html(Stream.empty().<Pair<String, String>>toArray(Pair[]::new), new String[0], func);

    assertThat(html, is("<html></html>"));
  }
}
